import test from 'node:test';
import assert from 'node:assert/strict';
import {createStudioBuffer} from '../shared/studio-buffer-store.js';
import {createStudioBufferServerStore} from '../shared/studio-buffer-server.js';
import {createStudioBufferClient,projectStudioBufferEditor} from '../shared/studio-buffer-client.js';
import {createStudioDocumentOpenStorage} from '../shared/studio-document-open-storage.js';
const id=n=>n.toString(16).padStart(48,'0');
async function setup(selected='prompt'){
 const workspaceId='open_client_workspace_001',server=createStudioBufferServerStore({hosting:{requireView:true,canonicalPath:p=>p}});
 const cap=server.issue({workspaceId,mode:'full'}).capability;let handle={},generation=server.bindHostingView(cap,'full',handle).generation;
 const initial={version:2,workspaceId,mode:'full',revision:1,savedAt:1,selectedBufferId:selected,activePromptId:'prompt',order:['prompt','doc'],buffers:[createStudioBuffer({id:'prompt',role:'prompt',text:'Original Prompt'}),createStudioBuffer({id:'doc',role:'document',text:'Original Document',resourceDir:'/old',metadata:{scratchpadKey:'draft:original',reviewNotesKey:'draft:original'}})]};
 assert(server.write(cap,null,initial,generation).ok);
 const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},key='piStudio.bufferWorkspace.v2:'+workspaceId;
 const makeClient=()=>createStudioBufferClient({workspaceId,mode:'full',switching:true,hosting:true,storage,makeBufferId:()=>{throw Error('unexpected migration');},canRestore:()=>true,getHostingGeneration:()=>generation,readRemote:async()=>server.read(cap),writeRemote:async(s,r,e)=>server.write(cap,r,s,generation,e),readLegacyRemote:async()=>({ok:true,state:null})});
 let client=makeClient();assert((await client.initialize(projectStudioBufferEditor(initial),'')).ok);await client.settled();
 const request=(n=1)=>{const p=client.hostingAuthority('doc');assert(p.ok);return{operationId:id(n),bufferId:'doc',documentEpoch:p.documentEpoch,expectedRevision:p.expectedRevision,path:'/next.py',sourcePath:'',resourceDir:'',discardTarget:true};};
 const file=()=>({ok:true,path:'/next.py',label:'next.py',text:'print(1)\n',diskRevision:'sha256:'+'a'.repeat(64),resourceDir:'/',editorLanguage:'python'});
 return {server,cap,storage,values,key,request,file,get client(){return client;},get generation(){return generation;},open:r=>server.hostingOpen(cap,{...r,operation:'open',generation},file),cancel:r=>server.hostingOpen(cap,{...r,operation:'open-cancel',generation}),async reload(){client.dispose();server.releaseHostingView(cap,handle);handle={};generation=server.bindHostingView(cap,'full',handle).generation;client=makeClient();const result=await client.initialize(projectStudioBufferEditor(initial),'');await client.settled();return result;}};
}
test('open adoption keeps newer unrelated Prompt work and checkpoint identity',async()=>{const f=await setup(),r=f.request(),before=f.client.snapshot();assert(f.client.beginOpen(r).ok);assert(f.values.has(f.key+':open'));assert(f.client.isHostingFrozen());assert(f.client.persist({...projectStudioBufferEditor(before),text:'Prompt typed during open'},'').ok);const result=f.open(r);assert(result.ok);const applied=f.client.finishOpen(result);assert(applied.ok,JSON.stringify(applied));assert.equal(applied.selectedChanged,false);await f.client.settled();assert.equal(f.client.snapshot().buffers[0].text,'Prompt typed during open');assert.equal(f.client.snapshot().buffers[1].id,'doc');assert.equal(f.client.snapshot().buffers[1].sourceState.path,'/next.py');assert.deepEqual(f.server.read(f.cap).state,f.client.snapshot());assert(!f.client.openBackup().record);assert(!f.client.needsUnloadConfirmation());});
for(const committed of [false,true])test(`reload freezes retained open before publication (${committed?'committed/lost reply':'request not delivered'})`,async()=>{const f=await setup(),r=f.request();assert(f.client.beginOpen(r).ok);assert(f.client.persist({...projectStudioBufferEditor(f.client.snapshot()),text:'Newer Prompt'},'').ok);if(committed)assert(f.open(r).ok);const loaded=await f.reload();assert(loaded.ok,JSON.stringify(loaded));assert(f.client.isHostingFrozen());assert(f.client.needsUnloadConfirmation());const result=committed?f.open(r):f.cancel(r);assert(f.client.finishOpen(result).ok);await f.client.settled();assert.equal(f.client.snapshot().buffers[0].text,'Newer Prompt');assert.equal(f.client.snapshot().buffers[1].text,committed?'print(1)\n':'Original Document');assert(!f.client.isHostingFrozen());});
test('quota or foreign storage keeps the opening backup and prevents false completion',async()=>{for(const foreign of [false,true]){const f=await setup(),r=f.request();assert(f.client.beginOpen(r).ok);const result=f.open(r),before=f.client.snapshot(),set=f.storage.setItem;if(foreign)f.values.set(f.key,'foreign recovery');else f.storage.setItem=()=>{throw Error('quota');};assert.equal(f.client.finishOpen(result).ok,false);assert(f.client.isHostingFrozen());assert(f.client.openBackup().record);assert.equal(f.client.snapshot(),before);if(foreign)assert.equal(f.values.get(f.key),'foreign recovery');else{f.storage.setItem=set;assert(f.client.finishOpen(result).ok);}}});
test('late affected text, changed lease, and unrelated-slot response tampering refuse adoption',async()=>{for(const kind of ['text','lease','prompt']){const f=await setup('doc'),r=f.request();assert(f.client.beginOpen(r).ok);let result=f.open(r);if(kind==='text')f.client.capture({...projectStudioBufferEditor(f.client.snapshot()),text:'Late DOM work'},'');if(kind==='lease')result={...result,generation:f.generation+1};if(kind==='prompt')result={...result,state:{...result.state,buffers:result.state.buffers.map(b=>b.id==='prompt'?{...b,text:'Wrong Prompt'}:b)}};assert.equal(f.client.finishOpen(result).ok,false,kind);assert(f.client.openBackup().record);assert(f.client.needsUnloadConfirmation());}});
test('retained backups reject lossy normalization instead of dropping unfamiliar work',async()=>{const f=await setup(),key=f.key+':open',before=structuredClone(f.client.snapshot());before.foreignNotes=['keep'];const raw=JSON.stringify({version:1,request:f.request(),before});f.values.set(key,raw);assert(createStudioDocumentOpenStorage(f.storage,key,{workspaceId:before.workspaceId,mode:'full'}).peek().error);assert.equal(f.values.get(key),raw);});
test('storage rejects corrupt/foreign records and changed CAS, including recheck after failed capture',async()=>{const f=await setup(),r=f.request(),key=f.key+':open',expected={workspaceId:f.client.snapshot().workspaceId,mode:'full'};for(const raw of ['{bad',JSON.stringify({version:1,request:r,before:{...f.client.snapshot(),workspaceId:'foreign_workspace_001'}})]){f.values.set(key,raw);assert(createStudioDocumentOpenStorage(f.storage,key,expected).peek().error);assert.equal(f.values.get(key),raw);}f.values.delete(key);const tracked=createStudioDocumentOpenStorage(f.storage,key,expected);assert(!tracked.peek().record);f.values.set(key,'foreign');assert.equal(tracked.capture({version:1,request:r,before:f.client.snapshot()}).ok,false);assert.equal(f.values.get(key),'foreign');});
