// Actual Working formatter/state/controller helpers. No SDK/provider/REPL.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../client/studio-client.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../client/studio.css',import.meta.url),'utf8'),index=fs.readFileSync(new URL('../index.ts',import.meta.url),'utf8');
function section(a,b){const x=source.indexOf(a),y=source.indexOf(b,x);assert(x>=0&&y>x,'missing '+a);return source.slice(x,y);}
const escape=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
class Node{constructor(key='',open=false){this.key=key;this.open=open;this.attrs={'data-trace-details-key':key,'data-trace-expected-open':String(open)};this.isConnected=true;this.tagName='DETAILS';this.editable=false;}matches(s){return s==='details[data-trace-details-key]';}getAttribute(k){return this.attrs[k]??null;}setAttribute(k,v){this.attrs[k]=String(v);}closest(){return this.editable?this:null;}}
function fixture(){const nodes=[],c={Element:Node,traceExpandedOutputs:new Set(),traceOpenDetails:new Set(),traceClosedDetails:new Set(),traceSectionDefaults:new Map(),traceAutoScroll:true,TRACE_OUTPUT_PREVIEW_MAX_LINES:50,TRACE_OUTPUT_PREVIEW_MAX_CHARS:8000,TRACE_SECTION_AUTO_OPEN_MAX_LINES:6,TRACE_SECTION_AUTO_OPEN_MAX_CHARS:600,rightView:'trace',readerActive:false,modal:false,escapeHtml:escape,formatCompactNumber:x=>String(x),normalizeFenceLanguage:x=>x,wrapHighlight:(cls,x)=>`<span class='${cls}'>${escape(x)}</span>`,EMPTY_OVERLAY_LINE:'',critiqueViewEl:{querySelectorAll:()=>nodes,contains:n=>nodes.includes(n)||n.inPane},studioLinkedReaderIsActive:()=>c.readerActive,studioModalBlocksDraftAction:()=>c.modal,isTextEntryShortcutTarget:n=>n?.editable===true,normalizeTraceImage:()=>null,renderTraceImages:()=>'',formatReferenceTime:x=>String(x||''),normalizeTraceFilter:x=>x||'all',traceFilter:'all',traceDisplayContext:{},traceState:{status:'running',entries:[]},createEmptyTraceState:()=>({status:'idle',entries:[]}),getTraceHistoryContextLabel:()=>'',buildVisibleWorkingText:()=> 'retained Working text'};
 c.getTraceEntriesForFilter=()=>c.traceState.entries;c.renderTraceViewIfActive=()=>{};vm.createContext(c);vm.runInContext(section('function formatTraceOutputSize(','function renderTraceImages('),c);vm.runInContext(section('function highlightCodeTokens(','function getEditorLanguageForPreview('),c);vm.runInContext(section('function handleTraceDetailsToggle(','function handleReplPaneClick('),c);vm.runInContext(section('function buildTracePanelHtml(','function renderTraceView('),c);return {c,nodes};}
const tool=(changes={})=>({id:'tool-one',type:'tool',toolName:'codemode',label:'Execute JavaScript',args:JSON.stringify({code:'  const value = 3;\n  console.log(value);'}),output:'3\n',images:[],status:'complete',isError:false,startedAt:1000,updatedAt:2250,...changes});
test('codemode JSON wrapper becomes Code with exact indentation and modest escaped JavaScript highlighting',()=>{const {c}=fixture(),entry=tool(),p=c.getTraceToolInputPresentation(entry);assert.equal(p.label,'Code');assert.equal(p.language,'javascript');assert.equal(p.text,'  const value = 3;\n  console.log(value);');const html=c.renderTraceToolInput(entry);assert.match(html,/hl-code-kw/);assert.match(html,/  <span/);assert(!html.includes('&quot;code&quot;'));assert(!html.includes('data-repl-action'));assert(!html.includes('textarea'));});
test('namespaced and raw codemode input retain literal source; unknown tool JSON stays Input',()=>{const {c}=fixture();for(const toolName of ['codemode','functions.codemode']){const p=c.getTraceToolInputPresentation(tool({toolName,args:'  await tools.read({path: "x"});\n'}));assert.equal(p.text,'  await tools.read({path: "x"});\n');assert.equal(p.label,'Code');}assert.equal(c.getTraceToolInputPresentation(tool({toolName:'unknown',args:'{"code":"example"}'})).label,'Input');});
test('codemode extra fields are not silently discarded; source is escaped rather than executed',()=>{const {c}=fixture();const html=c.renderTraceToolInput(tool({args:JSON.stringify({code:'  const x = "</pre><script>bad()</script>";',metadata:'kept'})}));assert(!html.includes('<script>'));assert(html.includes('&lt;'));assert(html.includes('metadata'));assert(html.includes('kept'));});
test('short section defaults visible and long section compact with summary/line count, independently',()=>{const {c}=fixture();assert.equal(c.traceSectionIsOpen('a','one\ntwo'),true);assert.equal(c.traceSectionIsOpen('b','x'.repeat(601)),false);assert.equal(c.traceSectionIsOpen('b',Array(8).fill('x').join('\n')),false);const html=c.buildTracePanelHtml.call(c);assert(html.includes('trace-toolbar'));c.traceState.entries=[tool({output:Array(15).fill('line').join('\n')})];const cards=c.buildTracePanelHtml();assert(cards.includes('Code ·'));assert(cards.includes('Output ·'));assert(cards.includes('15 lines'));assert(!cards.includes("data-trace-details-key='tool-one:output' data-trace-expected-open='true'"));});
test('native initial-open toggle does not invent a user expansion or stop streaming Follow',()=>{const {c,nodes}=fixture(),node=new Node('a',true);nodes.push(node);c.handleTraceDetailsToggle({target:node});assert.equal(c.traceOpenDetails.size,0);assert.equal(c.traceClosedDetails.size,0);assert.equal(c.traceAutoScroll,true);});
test('explicit collapse and expansion survive streamed text growth and never affect the other section',()=>{const {c,nodes}=fixture(),node=new Node('tool-one:input',true);nodes.push(node);node.open=false;c.handleTraceDetailsToggle({target:node});assert(c.traceClosedDetails.has(node.key));assert.equal(c.traceSectionIsOpen(node.key,'short'),false);assert.equal(c.traceSectionIsOpen('tool-one:output','short'),true);node.open=true;c.handleTraceDetailsToggle({target:node});assert.equal(c.traceSectionIsOpen(node.key,'x'.repeat(50000)),true);assert(!c.traceClosedDetails.has(node.key));assert.equal(c.traceAutoScroll,false);});
test('summary activation commits explicit choice synchronously before a streaming rerender can detach the node',()=>{const {c,nodes}=fixture(),detail=new Node('stream:input',false),summary=new Node();summary.tagName='SUMMARY';summary.parentElement=detail;summary.closest=s=>s==='summary'?summary:null;nodes.push(detail,summary);c.handleTracePaneClick({target:summary,defaultPrevented:false,preventDefault(){}});assert(c.traceOpenDetails.has(detail.key));assert.equal(c.traceSectionIsOpen(detail.key,'x'.repeat(50000)),true);detail.isConnected=false;detail.open=true;c.handleTraceDetailsToggle({target:detail});assert(c.traceOpenDetails.has(detail.key));});
test('queued toggles from detached/foreign/reader nodes cannot change current Working choices',()=>{for(const kind of ['detached','foreign','reader','view']){const {c,nodes}=fixture(),node=new Node('a',true);if(kind!=='foreign')nodes.push(node);node.open=false;if(kind==='detached')node.isConnected=false;if(kind==='reader')c.readerActive=true;if(kind==='view')c.rightView='preview';c.handleTraceDetailsToggle({target:node});assert.equal(c.traceClosedDetails.size,0,kind);}});
test('Collapse/Expand affects only currently displayed details, not hidden-filter choices or full-output bounds',()=>{const {c,nodes}=fixture();nodes.push(new Node('shown-input',true),new Node('shown-output',false));c.traceOpenDetails.add('hidden');c.traceExpandedOutputs.add('shown-output');c.setTraceVisibleDetails(false);assert(nodes.every(n=>!n.open));assert(c.traceOpenDetails.has('hidden'));assert(c.traceExpandedOutputs.has('shown-output'));c.setTraceVisibleDetails(true);assert(nodes.every(n=>n.open));assert.equal(c.traceAutoScroll,false);assert(nodes.every(n=>n.getAttribute('data-trace-expected-open')==='true'));});
test('bulk toolbar controls preserve filters/copy/load and do not add a whole-card nesting layer',()=>{const {c}=fixture();c.traceState.entries=[tool()];const html=c.buildTracePanelHtml();for(const action of ['collapse','expand','copy','load'])assert(html.includes(`data-trace-action='${action}'`));for(const filter of ['all','thinking','tools'])assert(html.includes(`data-trace-filter='${filter}'`));assert(!html.includes('<details class=\'trace-card'));assert(html.includes("<article class='trace-card trace-card-tool'"));});
test('full/preview remains bounded separately from fold expansion and highlighting escapes truncation',()=>{const {c}=fixture(),text='  const x = "<script>";\n'.repeat(1000);const preview=c.renderTraceOutput(text,'a',{label:'Code',language:'javascript'});assert(preview.includes('Show full code'));assert(!preview.includes('<script>'));c.traceExpandedOutputs.add('a');const full=c.renderTraceOutput(text,'a',{label:'Code',language:'javascript'});assert(full.includes('Collapse code'));assert(full.length>preview.length);});
test('collapsed errors remain explicit and red even when entry status is complete; timing/tool/status are retained',()=>{const {c}=fixture();c.traceState.entries=[tool({isError:true,status:'complete',output:'failure\n'.repeat(100)})];const html=c.buildTracePanelHtml();assert(html.includes('trace-entry-status-error'));assert(html.includes('Error'));assert(html.includes('codemode'));assert(html.includes('1.3s'));assert(html.includes('is-error'));assert(html.includes('Output ·'));});
test('explicit error status remains an error even without the separate error flag',()=>{const {c}=fixture();c.traceState.entries=[tool({isError:false,status:'error',output:'Failure fixture\n'.repeat(100)})];const html=c.buildTracePanelHtml();assert(html.includes('trace-entry-status-error'));assert(html.includes('is-error'));assert(html.includes('Output · Error'));assert(!html.includes('>Complete</span>'));});
function keyEvent(target,changes={}){return {target,ctrlKey:true,shiftKey:true,metaKey:false,altKey:false,code:'BracketLeft',key:'{',repeat:false,isComposing:false,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...changes};}
test('Control+Shift+[ / ] is Working-content local, keyboard accessible and excludes editors/modal/reader/composition/repeats',()=>{const {c,nodes}=fixture(),n=new Node('a',true);nodes.push(n);const collapse=keyEvent(n);c.handleTracePaneKeydown(collapse);assert(collapse.defaultPrevented);assert.equal(n.open,false);const expand=keyEvent(n,{code:'BracketRight',key:'}'});c.handleTracePaneKeydown(expand);assert(expand.defaultPrevented);assert.equal(n.open,true);for(const change of [{repeat:true},{isComposing:true},{metaKey:true},{altKey:true},{ctrlKey:false},{shiftKey:false},{defaultPrevented:true},{code:'KeyC',key:'C'}]){const e=keyEvent(n,change);c.handleTracePaneKeydown(e);assert.equal(n.open,true);}for(const condition of ['editable','outside','reader','modal','view']){n.open=true;const target=condition==='outside'?new Node('other'):n;n.editable=condition==='editable';c.readerActive=condition==='reader';c.modal=condition==='modal';c.rightView=condition==='view'?'repl':'trace';const e=keyEvent(target);c.handleTracePaneKeydown(e);assert.equal(n.open,true,condition);assert.equal(e.defaultPrevented,false,condition);}});
test('output images remain inside their own fold and existing image policy is retained',()=>{const {c}=fixture();c.renderTraceImages=()=>'<div class="trace-image-gallery">image preserved</div>';c.traceState.entries=[tool({output:'',images:[{label:'fixture'}]})];const html=c.buildTracePanelHtml();assert(html.includes('image preserved'));assert(html.includes('1 image'));assert(html.includes("data-trace-details-key='tool-one:output'"));});
test('single-image output retains text-size default and then its first-content pin; multiple images start compact',()=>{
 const {c}=fixture(),long='long image caption\n'.repeat(75);
 assert(c.renderTraceSection('Output',long,'one-long','',{imageCount:1}).includes("data-trace-expected-open='false'"));
 assert(c.renderTraceSection('Output','short','one-long','',{imageCount:1}).includes("data-trace-expected-open='false'"));
 assert(c.renderTraceSection('Output','short','one-short','',{imageCount:1}).includes("data-trace-expected-open='true'"));
 assert(c.renderTraceSection('Output','short','many','',{imageCount:2}).includes("data-trace-expected-open='false'"));
});
test('code whitespace selector outranks rendered-markdown pre without changing general output wrapping',()=>{assert(css.includes(".trace-output.trace-output-code {"));});
test('nested Raw, Write and Edit disclosures mark parser state and preserve explicit collapse over full output',()=>{
 const {c,nodes}=fixture(),text='line\n'.repeat(70);
 const cases=[['raw:raw-input',()=>c.renderTraceRawInputDetails(text,'raw'),['raw:raw-input']],['write:content',()=>c.renderTraceToolTextDetails('Content',text,'write:content','Content'),['write:content']],['edit:edit:0',()=>c.renderTraceEditInput({id:'edit'},{edits:[{oldText:text,newText:text}]},'{}'),['edit:edit:0:old','edit:edit:0:new']]];
 for(const [key,render,fullKeys] of cases){
  c.traceOpenDetails.add(key);let html=render();const marker=`data-trace-details-key='${key}' data-trace-expected-open='true' open`;
  assert(html.includes(marker),key+' must mark remembered-open parser insertion');
  const n=new Node(key,true);n.attrs['data-trace-expected-open']=html.includes(marker)?'true':null;nodes.push(n);c.traceAutoScroll=true;c.handleTraceDetailsToggle({target:n});assert.equal(c.traceAutoScroll,true,key+' parser toggle cannot stop Follow');
  for(const k of fullKeys)c.traceExpandedOutputs.add(k);c.setTraceVisibleDetails(false);html=render();assert(html.includes(`data-trace-details-key='${key}' data-trace-expected-open='false'>`),key+' full output must not undo collapse');
  c.setTraceVisibleDetails(true);assert(render().includes(marker));
 }
});
test('untouched streaming sections keep their first-content default through growth and shrink, independently',()=>{
 const {c}=fixture();assert.equal(c.traceSectionIsOpen('live','short'),true);assert.equal(c.traceSectionIsOpen('live','x'.repeat(20000)),true);
 assert.equal(c.traceSectionIsOpen('complete','x'.repeat(20000)),false);assert.equal(c.traceSectionIsOpen('complete','short'),false);
 c.traceClosedDetails.add('live');assert.equal(c.traceSectionIsOpen('live','short'),false);c.traceClosedDetails.delete('live');assert.equal(c.traceSectionIsOpen('live','long'.repeat(1000)),true);
});
test('pending empty output does not freeze the default before actual text or images arrive',()=>{
 const {c}=fixture();c.renderTraceSection('Output','','pending','',{pending:true});assert.equal(c.traceSectionDefaults.has('pending'),false);
 c.renderTraceSection('Output','x'.repeat(20000),'pending','',{pending:true});assert.equal(c.traceSectionIsOpen('pending','short'),false);
 c.renderTraceSection('Output','','image','',{imageCount:1,pending:true});assert.equal(c.traceSectionDefaults.get('image'),true);
 assert(c.renderTraceSection('Output','','image','',{imageCount:3}).includes("data-trace-expected-open='true'"));
});
test('new run clears cached initial defaults together with explicit choices; same run keeps them',()=>{
 const {c}=fixture();c.normalizeTraceState=x=>x;vm.runInContext(section('function replaceTraceState(','function upsertTraceEntry('),c);
 c.traceState.runId='old';c.traceSectionIsOpen('section','short');c.traceOpenDetails.add('explicit');
 c.replaceTraceState({runId:'old',entries:[]});assert.equal(c.traceSectionDefaults.get('section'),true);assert(c.traceOpenDetails.has('explicit'));
 c.replaceTraceState({runId:'new',entries:[]});assert.equal(c.traceSectionDefaults.size,0);assert.equal(c.traceOpenDetails.size,0);assert.equal(c.traceSectionIsOpen('section','long'.repeat(5000)),false);
});
test('new-run reset and keyboard wiring preserve existing state/filter/shortcut ownership',()=>{assert.match(section('function replaceTraceState(','function upsertTraceEntry('),/traceClosedDetails\.clear\(\)/);assert(source.includes('addEventListener("keydown", handleTracePaneKeydown)'));assert.match(index,/Control.*Shift.*\[/);assert.match(css,/\.trace-output-code/);assert.match(css,/white-space: pre;/);assert.match(css,/\.trace-section-fold\.is-error/);});
