import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {saveStudioDiskFileAs,readStudioDiskFileSnapshot} from '../shared/studio-disk-revisions.js';
const source=fs.readFileSync(new URL('../index.ts',import.meta.url),'utf8');
function helper(){
 const a=source.indexOf('function writeStudioHostedHtmlDocumentExport('),b=source.indexOf('function writeStudioFile(',a);
 assert(a>=0&&b>a,'guarded hosted HTML writer missing');
 const code=source.slice(a,b).replace(/^function writeStudioHostedHtmlDocumentExport\([\s\S]*?\): \{ filePath: string \| null; diskRevision: string \| null; error: string \| null \} \{/, 'function writeStudioHostedHtmlDocumentExport(path,data,cwd,authorizeCommit) {').replace('(canonical: string)', '(canonical)');
 const c={saveStudioDiskFileAs};vm.createContext(c);vm.runInContext(code,c);return c.writeStudioHostedHtmlDocumentExport;
}
function fixture(t){const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'studio-html-write-')));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
const html=Buffer.from('<!doctype html><h1>Generated λ</h1>');
test('guarded HTML writer creates exact new bytes using existing Save As revision contract',t=>{
 const dir=fixture(t),file=path.join(dir,'new.html'),authorized=[];const r=helper()(file,html,dir,p=>{authorized.push(p);return {ok:true};});
 assert.equal(r.filePath,file);assert.equal(r.error,null);assert.deepEqual(fs.readFileSync(file),html);assert(authorized.length>0&&authorized.every(p=>p===file));assert.equal(r.diskRevision,readStudioDiskFileSnapshot(file).revision);
});
test('guarded HTML writer never overwrites an existing export or editable backing',t=>{
 const dir=fixture(t),file=path.join(dir,'existing.html');fs.writeFileSync(file,'retained unsaved baseline');const r=helper()(file,html,dir,()=>({ok:true}));
 assert.equal(r.filePath,null);assert(r.error);assert.equal(fs.readFileSync(file,'utf8'),'retained unsaved baseline');assert.equal(r.diskRevision,null);assert.equal(html.toString(),'<!doctype html><h1>Generated λ</h1>');
});
test('final authorization refuses an owned or pending-save target even if it is absent',t=>{
 const dir=fixture(t),file=path.join(dir,'claimed.html'),r=helper()(file,html,dir,()=>({ok:false,message:'Another Document holds this target.'}));
 assert.equal(r.filePath,null);assert.match(r.error,/Another Document/);assert(!fs.existsSync(file));
});
test('missing/ambiguous authorization fails closed before writing or creating directories',t=>{
 const dir=fixture(t),file=path.join(dir,'missing','new.html'),write=helper();
 for(const authorize of [undefined,null]){const r=write(file,html,dir,authorize);assert.equal(r.filePath,null);assert(r.error);assert(!fs.existsSync(path.dirname(file)));}
 for(const authorize of [()=>undefined,()=>({}),()=>({ok:'yes'}),()=>Promise.resolve({ok:true})]){const r=write(path.join(dir,'ambiguous.html'),html,dir,authorize);assert.equal(r.filePath,null);assert(r.error);assert(!fs.existsSync(path.join(dir,'ambiguous.html')));}
});
test('authorization errors and actual disk failures preserve generated bytes without fake save receipt',t=>{
 const dir=fixture(t),write=helper(),file=path.join(dir,'refused.html');const refused=write(file,html,dir,()=>{throw Error('owner lookup unavailable');});assert.equal(refused.filePath,null);assert.match(refused.error,/owner lookup unavailable/);assert(!fs.existsSync(file));
 const blocked=path.join(dir,'directory.html');fs.mkdirSync(blocked);const r=write(blocked,html,dir,()=>({ok:true}));assert.equal(r.filePath,null);assert(r.error);assert.equal(r.diskRevision,null);assert(html.includes(Buffer.from('Generated λ')));
});
test('an existing symlink never overwrites the linked file',t=>{
 const dir=fixture(t),original=path.join(dir,'original.html'),alias=path.join(dir,'alias.html');fs.writeFileSync(original,'keep original');fs.symlinkSync(original,alias);const r=helper()(alias,html,dir,()=>({ok:true}));assert.equal(r.filePath,null);assert(r.error);assert.equal(fs.readFileSync(original,'utf8'),'keep original');
});
