import test from 'node:test';import assert from 'node:assert/strict';
const deferred=()=>{let resolve;return {promise:new Promise(r=>resolve=r),resolve};};
async function fixture(request){const {createStudioDocumentOpenController}=await import('../shared/studio-document-open-client.js');let record=null,generation=1;const calls=[];
 const client={openBackup:()=>({record}),hostingAuthority:()=>({ok:true,bufferId:'doc',expectedRevision:'a'.repeat(48),documentEpoch:1}),beginOpen:r=>{record={request:r,before:{}};return{ok:true};},finishOpen:r=>{calls.push('finish');record=null;return{ok:true,selectedChanged:true,status:r.status};},settled:async()=>{}};
 const controller=createStudioDocumentOpenController({client:()=>client,generation:()=>generation,makeOperationId:()=> 'b'.repeat(48),prepare:async()=>{},busy:()=>false,request:async b=>{calls.push(b);return b.operation==='open-ack'?{ok:true}:request(b);},capture:()=>{},domCurrent:()=>true,bind:()=>calls.push('bind'),replace:()=>calls.push('replace'),changed:()=>{},status:m=>calls.push(m),reuse:async()=>true});
 return{controller,client,calls,get record(){return record;},set generation(n){generation=n;}};}
const input={bufferId:'doc',path:'/next.py',sourcePath:'',resourceDir:''};
test('same-flight presses coalesce; adoption binds before releasing the receipt',async()=>{const held=deferred(),f=await fixture(()=>held.promise),a=f.controller.open(input),b=f.controller.open(input);await new Promise(r=>setImmediate(r));assert.equal(f.calls.filter(x=>x.operation==='open').length,1);held.resolve({ok:true,status:'committed'});assert((await a).ok);await b;assert.equal(f.calls.filter(x=>x==='bind').length,1);assert(f.calls.indexOf('bind')<f.calls.findIndex(x=>x.operation==='open-ack'));});
test('lost reply retains the exact intent for recheck, not a second identity',async()=>{let n=0;const f=await fixture(()=>++n===1?Promise.reject(Error('lost reply')):{ok:true,status:'committed'});assert.equal((await f.controller.open(input)).ok,false);const first=f.record.request;assert(f.controller.active());assert((await f.controller.recheck()).ok);const sent=f.calls.filter(x=>x.operation==='open');assert.equal(sent.length,2);assert.equal(sent[0].operationId,first.operationId);assert.deepEqual(sent[0],sent[1]);});
test('cancel can overtake a held original response and late completion has no effects',async()=>{const held=deferred(),f=await fixture(b=>b.operation==='open-cancel'?{ok:true,status:'cancelled'}:held.promise),pending=f.controller.open(input);await new Promise(r=>setImmediate(r));assert((await f.controller.cancel()).ok);const effects=f.calls.filter(x=>typeof x==='string');held.resolve({ok:true,status:'committed'});await pending;assert.deepEqual(f.calls.filter(x=>typeof x==='string'),effects);assert(!f.record);});
test('changed lease or disposal prevents late response adoption',async()=>{for(const disposed of [true,false]){const held=deferred(),f=await fixture(()=>held.promise),pending=f.controller.open(input);await new Promise(r=>setImmediate(r));if(disposed)f.controller.dispose();else f.generation=2;held.resolve({ok:true,status:'committed'});await pending;assert(f.record);assert(!f.calls.includes('finish'));assert(!f.calls.includes('bind'));}});
