import test from 'node:test';import assert from 'node:assert/strict';
import {createStudioBuffer} from '../shared/studio-buffer-store.js';
import {createStudioBufferServerStore} from '../shared/studio-buffer-server.js';
import {createStudioDocumentLaunchController} from '../shared/studio-document-launch-client.js';
const id=n=>n.toString(16).padStart(48,'0'),exportId='12345678-1234-4234-9234-123456789abc',html='<!doctype html><h1>Kept output</h1>';
function fixture(options={}){const server=createStudioBufferServerStore({...options,hosting:{requireView:true,canonicalPath:p=>p,...options.hosting}}),workspaceId='origin_html_export_workspace_01',cap=server.issue({workspaceId,mode:'full'}).capability,handle={};let generation=server.bindHostingView(cap,'full',handle).generation;const p=createStudioBuffer({id:'prompt',role:'prompt',text:'Prompt work'}),d=createStudioBuffer({id:'doc',role:'document',text:'Unsaved work',resourceDir:'/old'});assert(server.write(cap,null,{version:2,workspaceId,mode:'full',revision:1,savedAt:1,selectedBufferId:d.id,activePromptId:p.id,order:[p.id,d.id],buffers:[p,d]},generation).ok);const request=(n=1,kind='blank',path='')=>({operationId:id(n),kind,path,sourcePath:'',resourceDir:'',bufferId:'doc',documentEpoch:server.read(cap).documents.doc,expectedRevision:server.read(cap).revision,generation,exportId});return {server,cap,request,workspaceId,reconnect(){server.releaseHostingView(cap,handle);generation=server.bindHostingView(cap,'full',{}).generation;return generation;}};}
const prepared=(r,scope)=>({ok:true,kind:r.kind,path:r.path||null,text:html,label:'result.html',resourceDir:'/approved',editorLanguage:'html',diskRevision:r.kind==='file'?'sha256:'+'a'.repeat(64):null});
test('prepared blank export creates real detached Document with retained HTML, no temporary backing or Prompt',()=>{const f=fixture(),before=f.server.read(f.cap),r=f.request();const a=f.server.hostingLaunch(f.cap,r,null,prepared);assert(a.ok);assert.equal(a.created,true);const w=f.server.hostedWorkspace(a.workspaceId),d=w.buffers[0];assert.equal(d.text,html);assert.equal(d.baselineText,'');assert.equal(d.sourceState.source,'import');assert.equal(d.sourceState.label,'result.html');assert.equal(d.sourceState.path,null);assert.equal(d.diskRevision,null);assert.equal(d.view.editorLanguage,'html');assert.equal(d.role,'document');assert.equal(w.activePromptId,null);assert.deepEqual(f.server.read(f.cap),before);});
test('prepared saved export registers matching file baseline and keeps original buffers',()=>{const f=fixture(),r=f.request(1,'file','/approved/result.html');const a=f.server.hostingLaunch(f.cap,r,p=>({ok:true,path:p,text:html,label:'result.html',diskRevision:'sha256:'+'a'.repeat(64),resourceDir:'/approved',editorLanguage:'html'}),prepared);assert(a.ok);const d=f.server.hostedWorkspace(a.workspaceId).buffers[0];assert.equal(d.text,html);assert.equal(d.baselineText,html);assert.equal(d.sourceState.path,r.path);assert.equal(d.diskRevision,'sha256:'+'a'.repeat(64));});
test('prepared source must be authenticated by synchronous loader before existing-owner reuse',()=>{const f=fixture(),r=f.request(1,'file','/approved/result.html');assert(f.server.hostingLaunch(f.cap,{...r,exportId:undefined},p=>({ok:true,path:p,text:'owned baseline',label:'owned.html',diskRevision:'sha256:'+'a'.repeat(64),resourceDir:'/approved'})).ok);const denied=f.server.hostingLaunch(f.cap,f.request(2,'file',r.path),()=>{throw Error('no read');},()=>({ok:false,reason:'export-expired',message:'Keep output'}));assert.equal(denied.ok,false);assert.equal(denied.reason,'export-expired');});
test('existing saved-file owner is reused without reloading or replacing its work',()=>{const f=fixture(),r=f.request(1,'file','/approved/result.html'),a=f.server.hostingLaunch(f.cap,r,p=>({ok:true,path:p,text:html,label:'result.html',diskRevision:'sha256:'+'a'.repeat(64),resourceDir:'/approved'}),prepared);assert(a.ok);const b=f.server.hostingLaunch(f.cap,f.request(2,'file',r.path),()=>{throw Error('owner must not reload');},prepared);assert(b.ok);assert.equal(b.bufferId,a.bufferId);assert.equal(b.created,false);});
test('receipt replay survives prepared expiry/reconnect and never registers another export',()=>{const f=fixture(),r=f.request(),a=f.server.hostingLaunch(f.cap,r,null,prepared);assert(a.ok);const replay=f.server.hostingLaunch(f.cap,{...r,generation:f.reconnect()},null,()=>{throw Error('original receipt precedes expired loader');});assert(replay.ok);assert.equal(replay.bufferId,a.bufferId);assert.equal(f.server.hostingLaunch(f.cap,{...r,generation:f.request().generation,exportId:'22345678-1234-4234-9234-123456789abc'},null,prepared).reason,'invalid-request');});
test('invalid/absent/async/mismatched prepared source fails without creating a blank replacement',()=>{for(const mode of ['id','missing','async','kind','path']){const f=fixture(),r=f.request(1,'file','/approved/result.html');const load=mode==='missing'?undefined:mode==='async'?async()=>prepared(r):()=>({...prepared(r),...(mode==='kind'?{kind:'blank'}:{}),...(mode==='path'?{path:'/wrong.html'}:{})});const a=f.server.hostingLaunch(f.cap,{...r,...(mode==='id'?{exportId:'bad'}:{})},()=>({ok:true,path:r.path,text:html}),load);assert.equal(a.ok,false,mode);assert.equal(f.server.hostingOwner(f.cap,r.path).owner,null);}});
test('late source generation, epoch or checkpoint change revokes export creation',()=>{for(const mode of ['generation','epoch','revision']){const f=fixture(),r=f.request(),load=()=>{if(mode==='generation')f.reconnect();else{const old=f.server.read(f.cap),next=structuredClone(old.state);next.revision++;next.savedAt++;if(mode==='epoch'){next.buffers[1].sourceState.label='Changed origin';next.buffers[1].revision++;}assert(f.server.write(f.cap,old.revision,next,r.generation,old.documents).ok);}return prepared(r);};assert.equal(f.server.hostingLaunch(f.cap,r,null,load).ok,false,mode);}});
test('oversized output and recovery capacity keep existing work without a receipt or owner',()=>{for(const mode of ['text','capacity']){const f=fixture(mode==='capacity'?{maxEntries:1}:{}),before=f.server.read(f.cap),r=f.request();const a=f.server.hostingLaunch(f.cap,r,null,()=>({...prepared(r),text:mode==='text'?'x'.repeat(900001):html}));assert.equal(a.ok,false);assert.deepEqual(f.server.read(f.cap),before);}});
test('export authority checks current owning proof and does not itself create/read/grant a Document',()=>{const f=fixture(),r=f.request(),before=f.server.read(f.cap);assert.equal(typeof f.server.hostingExportAuthority,'function');const a=f.server.hostingExportAuthority(f.cap,r);assert(a.ok);assert.equal(a.workspaceId,f.workspaceId);for(const bad of [{generation:0},{documentEpoch:r.documentEpoch+1},{expectedRevision:id(999)},{bufferId:'missing'}])assert.equal(f.server.hostingExportAuthority(f.cap,{...r,...bad}).ok,false);assert.deepEqual(f.server.read(f.cap),before);});
function client(t,overrides={}){const map=new Map(),calls=[],opened=[],messages=[];const o={workspaceId:'origin',storage:{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},generation:()=>1,prepare:async()=>{},authority:()=>({ok:true,bufferId:'doc',documentEpoch:1,expectedRevision:id(1)}),busy:()=>false,changed(){},status:m=>messages.push(m),confirm:async()=>true,open:(...a)=>opened.push(a),request:async r=>{calls.push(r);return r.operation==='launch'?{ok:true,operationId:r.operationId,created:true,bufferId:'created',workspaceId:'target'}:{ok:true,owner:{bufferId:r.bufferId,workspaceId:'target'},url:'/owned',live:false,seen:false};},...overrides};const c=createStudioDocumentLaunchController(o);t.after(()=>c.dispose());return {c,o,map,calls,opened,messages};}
const held=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('prepared launch retains exportId through original lost-reply retry, without text or tokens',async t=>{const f=client(t);f.o.request=async r=>{f.calls.push(r);throw Error('lost');};await f.c.start({kind:'blank',exportId});const raw=f.map.get('piStudio.bufferWorkspace.v2:origin:launch');assert(raw);assert.equal(JSON.parse(raw).request.exportId,exportId);assert(!raw.includes(html));f.o.request=async r=>{f.calls.push(r);return r.operation==='launch'?{ok:true,operationId:r.operationId,created:true,bufferId:'created',workspaceId:'target'}:{ok:true,owner:{bufferId:r.bufferId,workspaceId:'target'},url:'/owned',live:false,seen:false};};await f.c.recheck();assert.equal(f.calls.filter(r=>r.operation==='launch')[1].exportId,exportId);assert.equal(f.calls.filter(r=>r.operation==='launch')[0].operationId,f.calls.filter(r=>r.operation==='launch')[1].operationId);assert.equal(f.c.state().record,null);});
test('late visible departure before checkpoint prevents prepared creation dispatch',async t=>{const h=held(),f=client(t,{prepare:()=>h.promise});let current=true;const work=f.c.start({kind:'blank',exportId},{current:()=>current,open(){throw Error('no open');}});current=false;h.resolve();await work;assert.equal(f.calls.length,0);assert.equal(f.map.size,0);});
test('late departure after creation retains verified discovery but never opens/focuses',async t=>{const h=held(),f=client(t);let current=true;f.o.request=async r=>{f.calls.push(r);return h.promise;};const work=f.c.start({kind:'blank',exportId},{current:()=>current,open(){throw Error('no open');}});while(!f.calls.length)await Promise.resolve();current=false;h.resolve({ok:true,operationId:f.calls[0].operationId,created:true,bufferId:'created',workspaceId:'target'});await work;assert.equal(f.opened.length,0);assert.equal(f.calls.length,1);assert.equal(f.c.state().record,null);assert.equal(f.c.state().destinations[0].bufferId,'created');});
test('prepared presenter keeps the exact pre-render checkpoint and does not silently prepare or borrow newer proof',async t=>{const f=client(t,{prepare(){throw Error('must not prepare again');},authority(){throw Error('must not borrow current proof');}}),retained=[];assert(await f.c.start({kind:'blank',exportId},{authority:{ok:true,bufferId:'doc',documentEpoch:1,expectedRevision:id(77)},current:()=>true,open(){},retained:d=>retained.push(d)}));assert.equal(f.calls[0].expectedRevision,id(77));assert.equal(retained[0].created,true);assert(Object.isFrozen(retained[0]));});
test('malformed prepared IDs fail closed before persistence or dispatch',async t=>{for(const bad of [null,'bad',[],{},'12345678-1234-4234-9234-123456789ABC']){const f=client(t);await f.c.start({kind:'blank',exportId:bad});assert.equal(f.calls.length,0);assert.equal(f.map.size,0);}});
test('current prepared export uses pending presenter rather than opening another window',async t=>{const f=client(t),presented=[];assert(await f.c.start({kind:'blank',exportId},{current:()=>true,open:(...a)=>presented.push(a)}));assert.equal(f.opened.length,0);assert.deepEqual(presented,[['/owned',false]]);assert.equal(f.c.state().record,null);});
