import test from 'node:test';import assert from 'node:assert/strict';
import {createStudioBuffer} from '../shared/studio-buffer-store.js';
import {createStudioBufferServerStore} from '../shared/studio-buffer-server.js';
const id=n=>n.toString(16).padStart(48,'0');
function fixture(){const server=createStudioBufferServerStore({hosting:{requireView:true,canonicalPath:p=>p}}),workspaceId='open_here_workspace_001',cap=server.issue({workspaceId,mode:'full'}).capability,handle={};let generation=server.bindHostingView(cap,'full',handle).generation;
 const prompt=createStudioBuffer({id:'prompt',role:'prompt',text:'Keep Prompt'}),doc=createStudioBuffer({id:'doc',role:'document',text:'Old draft',resourceDir:'/old',metadata:{scratchpadKey:'draft:old',reviewNotesKey:'draft:old'}});
 assert(server.write(cap,null,{version:2,workspaceId,mode:'full',revision:1,savedAt:1,selectedBufferId:'prompt',activePromptId:'prompt',order:['prompt','doc'],buffers:[prompt,doc]},generation).ok);
 const request=(n=1)=>({operation:'open',operationId:id(n),bufferId:'doc',documentEpoch:server.read(cap).documents.doc,expectedRevision:server.read(cap).revision,generation,path:'/new.py',sourcePath:'',resourceDir:'',discardTarget:true});
 const file=()=>({ok:true,path:'/new.py',label:'new.py',text:'print(1)\n',diskRevision:'sha256:'+ 'a'.repeat(64),resourceDir:'/',editorLanguage:'python'});
 return{server,cap,request,file,reconnect(){server.releaseHostingView(cap,handle);generation=server.bindHostingView(cap,'full',{}).generation;return generation;}};}
test('open atomically preserves slot identity, Prompt and role while replacing only the file snapshot',()=>{const f=fixture(),before=f.server.read(f.cap),r=f.request();let reads=0;const result=f.server.hostingOpen(f.cap,r,()=>{reads++;return f.file();});assert(result.ok);assert.equal(result.status,'committed');const after=f.server.read(f.cap);assert.deepEqual(after.state.buffers[0],before.state.buffers[0]);assert.equal(after.state.selectedBufferId,'prompt');const d=after.state.buffers[1];assert.equal(d.id,'doc');assert.equal(d.role,'document');assert.equal(d.text,d.baselineText);assert.equal(d.view.editorLanguage,'python');assert.equal(d.metadata.scratchpadKey,'file:/new.py');assert.equal(after.lineage.at(-1).slot.beforeId,'doc');assert.equal(after.lineage.at(-1).slot.afterId,'doc');assert.equal(f.server.hostingOpen(f.cap,{...r,generation:f.reconnect()},()=>{throw Error('must not read twice');}).status,'committed');assert.equal(reads,1);assert.equal(f.server.hostingOpen(f.cap,{...r,path:'/different.py',generation:f.request().generation},f.file).reason,'invalid-request');});
test('cancellation fences delayed original requests without replacing anything',()=>{const f=fixture(),r=f.request(),before=f.server.read(f.cap);const cancelled=f.server.hostingOpen(f.cap,{...r,operation:'open-cancel'});assert(cancelled.ok);assert.equal(cancelled.status,'cancelled');assert.notEqual(f.server.read(f.cap).revision,before.revision);assert.deepEqual(f.server.read(f.cap).state.buffers,before.state.buffers);assert.equal(f.server.hostingOpen(f.cap,r,()=>{throw Error('late open must not read');}).status,'cancelled');});
test('an existing owner wins, including when it arrives during the authorized read',()=>{const f=fixture(),r=f.request();let winner;const result=f.server.hostingOpen(f.cap,r,()=>{winner=f.server.hostingLaunch(f.cap,{...r,kind:'file',operationId:id(77)},f.file);assert(winner.ok);return f.file();});assert(result.ok);assert.equal(result.status,'reused');assert.equal(result.owner.bufferId,winner.bufferId);assert.equal(f.server.read(f.cap).state.buffers[1].text,'Old draft');});
test('missing replacement consent and stale authority fail before reading',()=>{const f=fixture(),r=f.request(),load=()=>{throw Error('must not read');};assert.equal(f.server.hostingOpen(f.cap,{...r,discardTarget:false},load).ok,false);assert.equal(f.server.hostingOpen(f.cap,{...r,generation:0},load).ok,false);assert.equal(f.server.hostingOpen(f.cap,{...r,documentEpoch:0},load).ok,false);});
test('repeated cancellation without receipt acknowledgements stays bounded and fences reclaimed intents',()=>{const f=fixture(),first=f.request();for(let n=1;n<=200;n++){const r=f.request(n);assert(f.server.hostingOpen(f.cap,{...r,operation:'open-cancel'}).ok);}assert.equal(f.server.hostingOpen(f.cap,first,()=>{throw Error('cannot revive old intent');}).reason,'conflict');});
test('an old open receipt cannot overwrite a newer acknowledged workspace',()=>{const f=fixture(),r=f.request();assert(f.server.hostingOpen(f.cap,r,f.file).ok);const current=f.server.read(f.cap),state=structuredClone(current.state);state.revision++;state.savedAt++;state.buffers[0].revision++;state.buffers[0].text='New Prompt';assert(f.server.write(f.cap,current.revision,state,r.generation,current.documents).ok);assert.equal(f.server.hostingOpen(f.cap,r,f.file).reason,'outcome-changed');assert.equal(f.server.read(f.cap).state.buffers[0].text,'New Prompt');});
test('failed authorization and changed canonical result do not mutate the workspace',()=>{const f=fixture(),r=f.request(),before=f.server.read(f.cap);assert.equal(f.server.hostingOpen(f.cap,r,()=>({ok:false,reason:'grant-required'})).reason,'grant-required');assert.equal(f.server.hostingOpen(f.cap,r,()=>({...f.file(),path:'/changed'})).reason,'source-changed');assert.deepEqual(f.server.read(f.cap),before);assert(f.server.hostingOpen(f.cap,{...r,operation:'open-cancel'}).ok);});
test('retained disk save blocks opening over its affected Document',()=>{const f=fixture(),r={...f.request(99),kind:'save-as',path:'/pending.py',content:'Old draft',expectedDiskRevision:null,overwrite:false,force:false};assert(f.server.hostingSave(f.cap,r,authorize=>{assert(authorize(r.path).ok);return{...f.file(),path:r.path,text:r.content};}).ok);assert.equal(f.server.hostingOpen(f.cap,f.request(),()=>{throw Error('must not read');}).reason,'save-ack-pending');});
test('cancel cannot roll back an already committed open',()=>{const f=fixture(),r=f.request();assert(f.server.hostingOpen(f.cap,r,f.file).ok);assert.equal(f.server.hostingOpen(f.cap,{...r,operation:'open-cancel'}).status,'committed');assert.equal(f.server.read(f.cap).state.buffers[1].sourceState.path,'/new.py');});
