import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import ts from 'typescript';
const client=readFileSync(new URL('../client/studio-client.js',import.meta.url),'utf8'),server=readFileSync(new URL('../index.ts',import.meta.url),'utf8');
function section(source,start,end){const a=source.indexOf(start),b=source.indexOf(end,a+start.length);assert(a>=0&&b>a);return source.slice(a,b);}
function controls(){const elements=new Map(['studioMoveDocumentBtn','studioCopyDocumentBtn','studioForgetCopyBtn','studioRecheckLaunchBtn','studioForgetLaunchBtn'].map(id=>[id,{}]));let copy={},launch={};const c=vm.createContext({documentHostingEnabled:true,documentHostingReady:true,documentHostingGeneration:1,documentHostingSaveResolution:null,uiBusy:false,pendingSaveOperations:new Map(),studioModalBlocksDraftAction:()=>false,document:{getElementById:id=>elements.get(id)},getStudioSelectedBuffer:()=>({role:'document'}),documentHostingController:{copyState:()=>copy,active:()=>null,launchState:()=>launch},documentOpenController:null,openCompanionBtn:{},sourceOpenCurrentTextCopyTabBtn:{},syncStudioDocumentDestinations(){},syncStudioOperationNotices(){}});vm.runInContext(section(client,'      function syncDocumentHostingControls()','      async function requestDocumentHosting('),c);return {c,elements,copy:value=>{copy=value;},launch:value=>{launch=value;},sync:()=>c.syncDocumentHostingControls()};}
test('confirmed destinations keep fresh Copy/New labels; only pending intent changes them to retry',()=>{const h=controls();h.copy({destinations:[{bufferId:'copy'}]});h.launch({destinations:[{kind:'blank'}]});h.sync();assert.equal(h.elements.get('studioCopyDocumentBtn').textContent,'Copy to new window');assert.equal(h.c.openCompanionBtn.textContent,'New Document window');assert.equal(h.elements.get('studioForgetCopyBtn').disabled,true);h.copy({record:{request:{operationId:'pending'}}});h.launch({record:{request:{kind:'blank'}}});h.sync();assert.equal(h.elements.get('studioCopyDocumentBtn').textContent,'Recheck copy attempt');assert.equal(h.c.openCompanionBtn.textContent,'Find new Document window');});
test('creation commands are disabled in flight or while source readiness/consent blocks them',()=>{const h=controls();h.copy({busy:true});h.launch({busy:true});h.sync();assert(h.elements.get('studioCopyDocumentBtn').disabled);assert(h.c.openCompanionBtn.disabled);h.copy({});h.launch({});h.c.documentHostingReady=false;h.sync();assert(h.elements.get('studioCopyDocumentBtn').disabled);assert(h.c.openCompanionBtn.disabled);});
test('completed unopened destination owns a truthful notice and Show action, not the fresh Copy button',()=>{const c=vm.createContext({documentHostingEnabled:true,documentHostingGeneration:1,wsState:'Ready',documentHostingController:{copyState:()=>({destinations:[{operationId:'completed',sourceBufferId:'old-prompt',bufferId:'copy',kind:'copy',created:true,live:false}]}),moveState:()=>({}),launchState:()=>({})},documentOpenController:null,bufferRecoveryClient:{handoffBackup:()=>({}),pendingHostingSaves:()=>[]}});vm.runInContext(section(client,'      function collectStudioOperationNotices()','      function syncStudioOperationNotices()'),c);const n=c.collectStudioOperationNotices().get('destination:completed');assert.match(n.message,/Copy made\. Couldn't confirm its window opened/);assert.equal(n.bufferId,'old-prompt');assert.equal(n.actions[0].controlId,'studioDestination-completed');assert(!n.actions.some(a=>a.controlId==='studioCopyDocumentBtn'));});
test('destination group hides only itself, keeps its heading, and Show delegates to retained-owner logic',()=>{
 const calls=[];const node=tag=>({tag,children:[],dataset:{},append(...children){for(const c of children){c.parentElement=this;this.children.push(c);}},replaceChildren(){this.children=[];},querySelectorAll(){return this.children.flatMap(c=>c.tag==='button'?[c]:c.querySelectorAll());},addEventListener(_type,fn){this.click=fn;}});
 const menu=node('menu'),c=vm.createContext({menu:{menu},studioDocumentDestinationsSection:null,makeStudioUiRefreshElement:(tag,_class,text)=>Object.assign(node(tag),{textContent:text}),appendStudioUiRefreshMenuSection:(m,heading)=>{const section=node('section');section.append(Object.assign(node('heading'),{textContent:heading}));m.append(section);return section;},documentHostingGeneration:1,wsState:'Ready',uiBusy:false,studioModalBlocksDraftAction:()=>false,closeStudioBufferActionMenus(){},closeStudioUiRefreshMenus(){},documentHostingController:{openDestination:d=>calls.push(d.operationId)}});
 vm.runInContext(section(client,'        const destinationsGroup = appendStudioUiRefreshMenuSection(', '        action("studioFindMovedDocumentBtn"'),c);vm.runInContext(section(client,'      function syncStudioDocumentDestinations(', '      function syncDocumentHostingControls()'),c);
 c.syncStudioDocumentDestinations({},{});assert.notEqual(menu.hidden,true);assert.equal(menu.children[0].hidden,true);
 c.syncStudioDocumentDestinations({destinations:[{operationId:'known',bufferId:'copy_doc',kind:'copy'}]},{});assert.equal(menu.children[0].hidden,false);assert.equal(menu.children[0].children[0].textContent,'Document windows');const button=menu.querySelectorAll()[0];assert.equal(button.id,'studioDestination-known');button.click({detail:1});button.click({detail:2});assert.deepEqual(calls,['known']);
});
test('New Document loader closes its Open menu before dispatch, restoring opener focus',()=>{
 const listeners=[],closed=[],open={},importFileBtn={},getEditorBtn={},openCompanionBtn={};const c=vm.createContext({open,importFileBtn,getEditorBtn,openCompanionBtn,loadMenu:{menu:{addEventListener:(_name,fn)=>listeners.push(fn)},close:value=>closed.push(value)}});
 vm.runInContext(section(client,'        loadMenu.menu.addEventListener("click", event => {','        if (clearWorkspaceBtn)'),c);listeners[0]({target:openCompanionBtn});assert.deepEqual(closed,[true]);
});
function endpoint(){const replies=[],sent=[];let owner={workspaceId:'destination',bufferId:'draft_doc',mode:'editor-only'},live=false,seen=true;const c=vm.createContext({capability:'cap',studioCwd:'/work',res:{},respondJson:(_res,status,body)=>replies.push({status,body}),studioBufferStateStore:{hostedDocumentOwner:id=>id===owner?.bufferId?owner:null,hostingOwner:()=>{throw Error('path lookup must not run');},seenHostingView:()=>seen,hostingViewAuthority:(_cap,generation)=>generation===1?{ok:true}:{ok:false,reason:'lease-stale'}},hostedConnections:new Map(),WebSocket:{OPEN:1},sendToClient:(_socket,m)=>sent.push(m),url:(id,mode)=>'/editor/'+id+'?mode='+mode});const code='function run(body){'+section(server,'\t\t\t\tif (body.operation === "owner") {','\t\t\t\tawait studioPersistentStateQueue.catch(')+'}';vm.runInContext(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,c);return {c,replies,sent,owner:value=>{owner=value;},live(){live=true;c.hostedConnections.set({readyState:1},{workspaceId:owner.workspaceId});},run:body=>{c.run({operation:'owner',...body});return replies.at(-1);}};}
test('actual owner responder accepts retained draft identity, reports seen separately, without file lookup/read/grant',()=>{const h=endpoint();const a=h.run({bufferId:'draft_doc'});assert.equal(a.status,200);assert.equal(a.body.owner.bufferId,'draft_doc');assert.equal(a.body.live,false);assert.equal(a.body.seen,true);assert.equal(h.sent.length,0);});
test('actual owner responder refuses invalid/ambiguous IDs and mismatched post-consent owners',()=>{for(const body of [{bufferId:'../escape'},{bufferId:'draft_doc',path:'/some.md'},{bufferId:'draft_doc',expectedOwner:{workspaceId:'other',bufferId:'draft_doc'}}]){const h=endpoint();assert(h.run(body).status>=400);assert.equal(h.sent.length,0);}});
test('actual owner focus needs current source generation and matching owner; lookup alone never focuses',()=>{const h=endpoint();h.live();assert.equal(h.run({bufferId:'draft_doc'}).body.live,true);assert.equal(h.sent.length,0);assert.equal(h.run({bufferId:'draft_doc',focus:true,generation:9}).status,409);assert.equal(h.sent.length,0);assert.equal(h.run({bufferId:'draft_doc',focus:true,generation:1,expectedOwner:{workspaceId:'destination',bufferId:'draft_doc'}}).status,200);assert.equal(h.sent.length,1);assert.equal(h.sent[0].type,'document_hosting_focus');});
